name: cars
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  dio: ^5.9.0
  loading_animation_widget: ^1.3.0
  flutter_secure_storage: ^9.2.4
  iconsax: ^0.0.8
  flutter_card_swiper: ^7.0.2
  animated_text_kit: ^4.2.2
  shimmer: ^2.0.0
  intl: ^0.20.2
  image_picker: ^1.1.2
  firebase_messaging:
  flutter_local_notifications: ^19.4.0
  firebase_crashlytics: ^5.0.0
  string_validator: ^1.2.0
  lottie: ^3.2.0
  smooth_page_indicator: ^1.2.1
  font_awesome_flutter: 10.5.0
  url_launcher: ^6.3.1
  location: ^7.0.1
  flutter_rating_bar: ^4.0.1
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/animations/
    - assets/logos/
    - assets/fonts/
  fonts:
    - family: Lora-Bold
      fonts:
        - asset: assets/fonts/Lora-Bold.ttf
    - family: Lora-Regular
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf
    - family: Lora-Medium
      fonts:
        - asset: assets/fonts/Lora-Medium.ttf
        
        # Flutter launcher icon configuration
        # Run 'flutter pub run flutter_launcher_icons' to generate icons